### ISSUE TITLE
关于RMSE的计算

### ISSUE THREAD

**Issue by pppLang** [SaoYan/Multiscale-Super-Spectral#1]
https://github.com/SaoYan/Multiscale-Super-Spectral/blob/a3fbffc45ec9d88a910129430528f28234fa82cd/utilities.py#L58

你好！ 请问这里RMSE的计算是否有误？

RMSE的计算应该是在平方后，先进行求和、取平均，再开方 ，[refenecne](https://blog.csdn.net/reallocing1/article/details/56292877)

但根据你的公式，你是先进行了开方，再进行求和、取平均。

不知道是否是我理解有误，望回复

**Comment by SaoYan** [comment]
Please refer to section 4.3 in my paper
