### ISSUE TITLE
The dataset download link

### ISSUE THREAD

**Issue by wuyujiji** [SaoYan/Multiscale-Super-Spectral#2]
Excuse me! I want to do some relative works and need the spectral dataset of NTIRE 2018 challenge. The download link that you provided is invalid, the reason perhaps is the competition has been completed. Could you please share the new download link of this dataset?

Thank you very much!

**Comment by SaoYan** [comment]
https://competitions.codalab.org/competitions/18034

**Comment by Shahnewaz-rvis** [comment]
Hi, 
the link you provided, I could not able to find any data set to download. 
Could you please look at this. 
Thanks a lot
